# Generated by Django 3.0.5 on 2020-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('job_profile_id', models.CharField(max_length=100)),
                ('job_profile', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
